name: Build JAGCS  

on:  
  push:  
    branches:  
      - main   
  pull_request:  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up Qt  
        uses: qpm/qpm@v1.0.0  
        with:  
          qt-version: '5.15'    

      - name: Install dependencies  
        run: |  
          sudo apt-get update  
          sudo apt-get install -y build-essential cmake  

      - name: Build the project  
        run: |  
          mkdir build  
          cd build  
          cmake ..  
          make  

      - name: Run tests  
        run: |  
          cd build  
          make test  
